FROM continuumio/anaconda3:2020.02

WORKDIR workspace

RUN conda install -y scikit-learn
# RUN apt update
# RUN apt install -y software-properties-common 
# RUN add-apt-repository -y ppa:deadsnakes/ppa
# RUN apt install -y python3.7

# RUN apt install -y wget libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
# RUN wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
# RUN chmod +x Anaconda3-2020.02-Linux-x86_64.sh